export const colors = {
  primary: {
    bg: "bg-primary",
    text: "text-white",
    bgDisable: "disabled:bg-gray-400",
    textDisable: "",
    border: "",
    hover: "hover:brightness-125",
  },
  "primary-outline": {
    bg: "",
    text: "text-primary",
    bgDisable: "disabled:bg-gray-400",
    textDisable: "",
    border: "",
    hover: "hover:brightness-125",
  },
  "primary-gray": {
    bg: "bg-gray-100",
    text: "text-primary",
    bgDisable: "disabled:bg-gray-400",
    textDisable: "",
    border: "",
    hover: "hover:brightness-125",
  },
  "primary-modern": {
    bg: "bg-primary-modern",
    text: "text-white",
    bgDisable: "disabled:bg-gray-400",
    textDisable: "",
    border: "",
    hover: "hover:bg-primary-comfort",
  },
  "primary-modern-outline": {
    bg: "",
    text: "text-primary-modern",
    bgDisable: "disabled:bg-gray-400",
    textDisable: "",
    border: "",
    hover: "hover:text-comfort",
  },
  "primary-modern-border": {
    bg: "",
    text: "text-primary-modern",
    bgDisable: "disabled:bg-gray-400",
    textDisable: "",
    border: "border border-primary-modern",
    hover: "hover:text-comfort",
  },
  foreground: {
    bg: "bg-foreground",
    text: "text-background",
    bgDisable: "disabled:bg-gray-400",
    textDisable: "",
    border: "border border-gray-dark shadow-lg",
    hover: "hover:brightness-125",
  },
  danger: {
    bg: "bg-danger",
    text: "text-foreground",
    bgDisable: "disabled:bg-gray-400",
    textDisable: "",
    border: "",
    hover: "hover:brightness-125",
  },
  "danger-outline": {
    bg: "",
    text: "text-danger",
    bgDisable: "disabled:bg-gray-400",
    textDisable: "",
    border: "",
    hover: "hover:brightness-125",
  },
  success: {
    bg: "bg-success",
    text: "text-foreground",
    bgDisable: "disabled:bg-gray-400",
    textDisable: "",
    border: "",
    hover: "hover:brightness-125",
  },
  "success-outline": {
    bg: "",
    text: "text-success",
    bgDisable: "disabled:bg-gray-400",
    textDisable: "",
    border: "",
    hover: "hover:brightness-125",
  },
};
